import { Vulnerability, SecuritySource, CompanyType } from '../types';

export const SECURITY_SOURCES: { name: SecuritySource; label: string; icon: string; count: number }[] = [
  { name: 'SIEM', label: 'Security Information & Event Mgmt', icon: 'ShieldCheck', count: 142 },
  { name: 'EDR', label: 'Endpoint Detection & Response', icon: 'Laptop', count: 68 },
  { name: 'IAM', label: 'Identity & Access Governance', icon: 'Key', count: 31 },
  { name: 'CSPM', label: 'Cloud Security Posture Mgmt', icon: 'Cloud', count: 54 },
  { name: 'SCA', label: 'Software Composition Analysis', icon: 'Box', count: 89 },
  { name: 'SAST', label: 'Static App Security Testing', icon: 'Code', count: 114 },
  { name: 'DAST', label: 'Dynamic App Security Testing', icon: 'Activity', count: 27 },
  { name: 'CISA KEV', label: 'Known Exploited Vulnerabilities', icon: 'Flame', count: 12 },
  { name: 'Threat Intelligence', label: 'Global Darknet Feeds', icon: 'Radio', count: 95 },
];

export const INDUSTRY_VULNERABILITIES: Record<CompanyType, Vulnerability[]> = {
  Banking: [
    {
      id: 'bnk-01-sqli',
      title: 'SQL Injection in Payment Gateway Endpoint',
      cwe: 'CWE-89',
      severity: 'Critical',
      exploitability: 'High',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Payment System',
      service: 'Payment System',
      status: 'Open',
      source: 'DAST',
      cveId: 'CVE-2024-3094',
      description: 'Unsanitized user input in payment settlement query allows arbitrary ledger command execution and fraudulent credit balances.',
    },
    {
      id: 'bnk-02-data',
      title: 'Sensitive Data Exposure in Unencrypted Customer Store',
      cwe: 'CWE-200',
      severity: 'High',
      exploitability: 'Medium',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Customer Database',
      service: 'Customer Portal',
      status: 'Open',
      source: 'CSPM',
      cveId: 'CVE-2024-21413',
      description: 'Customer PII and bank account credentials stored with weak reversible encryption; susceptible to database dump exfiltration.',
    },
    {
      id: 'bnk-03-auth',
      title: 'Broken Authentication in Online Banking Gateway',
      cwe: 'CWE-287',
      severity: 'High',
      exploitability: 'High',
      businessImpact: 'High',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Authentication System',
      service: 'APIs',
      status: 'Open',
      source: 'SAST',
      cveId: 'CVE-2023-4863',
      description: 'JWT signature verification bypassed when alg header is forged to None, granting full impersonation of retail bank accounts.',
    },
    {
      id: 'bnk-04-pwd',
      title: 'Weak Password Policy on Internal Employee Portal',
      cwe: 'CWE-521',
      severity: 'Medium',
      exploitability: 'Medium',
      businessImpact: 'Medium',
      assetCriticality: 'MEDIUM',
      complianceImpact: 'Medium',
      asset: 'Employee Systems',
      service: 'Employee Portal',
      status: 'Open',
      source: 'IAM',
      cveId: 'CWE-521',
      description: 'Internal teller portal lacks mandatory MFA enforcement, allowing dictionary-based brute force password spraying.',
    },
    {
      id: 'bnk-05-lib',
      title: 'Outdated Apache Struts Library with Remote Code Execution',
      cwe: 'CWE-1104',
      severity: 'High',
      exploitability: 'Medium',
      businessImpact: 'High',
      assetCriticality: 'HIGH',
      complianceImpact: 'Medium',
      asset: 'Cloud Infrastructure',
      service: 'Customer Portal',
      status: 'Open',
      source: 'SCA',
      cveId: 'CVE-2024-21626',
      description: 'Vulnerable XML parsing library allows remote attackers to execute arbitrary system shell commands on transaction servers.',
    },
    {
      id: 'bnk-06-api',
      title: 'Exposed B2B Payment Clearing API Secret Key',
      cwe: 'CWE-798',
      severity: 'High',
      exploitability: 'High',
      businessImpact: 'High',
      assetCriticality: 'HIGH',
      complianceImpact: 'High',
      asset: 'Payment System',
      service: 'APIs',
      status: 'Open',
      source: 'SAST',
      cveId: 'CWE-798',
      description: 'Production NEFT / RTGS banking settlement Bearer secret leaked in staging client scripts, permitting unauthorized wire transfers.',
    },
    {
      id: 'bnk-07-ransom',
      title: 'Ransomware Lateral Movement Exposure via SMBv1',
      cwe: 'CWE-269',
      severity: 'Critical',
      exploitability: 'High',
      businessImpact: 'Critical',
      assetCriticality: 'HIGH',
      complianceImpact: 'High',
      asset: 'Cloud Infrastructure',
      service: 'Employee Portal',
      status: 'Open',
      source: 'CISA KEV',
      cveId: 'CVE-2024-1709',
      description: 'Unsegmented corporate branch subnets allow automated ransomware encryptor payloads to traverse domain controllers.',
    },
  ],

  Healthcare: [
    {
      id: 'hlth-01-ehr',
      title: 'Unencrypted Protected Health Information (PHI) in Clinical Store',
      cwe: 'CWE-311',
      severity: 'Critical',
      exploitability: 'High',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Electronic Health Records',
      service: 'EHR System',
      status: 'Open',
      source: 'CSPM',
      cveId: 'CVE-2024-1029',
      description: 'Patient medical histories, diagnostic diagnoses, and social security IDs stored unencrypted in clinical data stores, violating HIPAA.',
    },
    {
      id: 'hlth-02-dicom',
      title: 'DICOM Medical Imaging Gateway Remote Code Execution',
      cwe: 'CWE-94',
      severity: 'Critical',
      exploitability: 'High',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Diagnostic Equipment',
      service: 'Telemedicine APIs',
      status: 'Open',
      source: 'DAST',
      cveId: 'CVE-2024-5231',
      description: 'Buffer overflow in PACS medical imaging parsing engine allows remote arbitrary code execution and hospital network takeover.',
    },
    {
      id: 'hlth-03-idor',
      title: 'Insecure Direct Object Reference in Pharmacy Dispensing API',
      cwe: 'CWE-639',
      severity: 'High',
      exploitability: 'High',
      businessImpact: 'High',
      assetCriticality: 'HIGH',
      complianceImpact: 'High',
      asset: 'Patient Database',
      service: 'Pharmacy System',
      status: 'Open',
      source: 'SAST',
      cveId: 'CWE-639',
      description: 'Manipulating prescriptionId parameters allows unauthorized retrieval and modification of scheduled drug dosage records.',
    },
    {
      id: 'hlth-04-iot',
      title: 'Clinical Infusion Pump Telemetry Protocol Spoofing',
      cwe: 'CWE-294',
      severity: 'High',
      exploitability: 'Medium',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Diagnostic Equipment',
      service: 'Telemedicine APIs',
      status: 'Open',
      source: 'Threat Intelligence',
      cveId: 'CVE-2023-7182',
      description: 'Unauthenticated wireless telemetry protocol enables tampering with bedside drug infusion telemetry feeds.',
    },
    {
      id: 'hlth-05-auth',
      title: 'Missing Multi-Factor Authentication on Doctor Telehealth Portal',
      cwe: 'CWE-308',
      severity: 'Medium',
      exploitability: 'High',
      businessImpact: 'High',
      assetCriticality: 'HIGH',
      complianceImpact: 'High',
      asset: 'Identity Provider',
      service: 'Patient Portal',
      status: 'Open',
      source: 'IAM',
      cveId: 'CWE-308',
      description: 'Physician remote telehealth login relies on single-factor passwords, exposing clinical consult logs to credential theft.',
    },
    {
      id: 'hlth-06-ransom',
      title: 'Ransomware Extortion Vulnerability Targeting Hospital PACS Server',
      cwe: 'CWE-284',
      severity: 'Critical',
      exploitability: 'High',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Electronic Health Records',
      service: 'EHR System',
      status: 'Open',
      source: 'CISA KEV',
      cveId: 'CVE-2024-21410',
      description: 'Unpatched vulnerability in Windows domain controller allows ransomware gangs to halt all clinical diagnostic workflows.',
    },
  ],

  'SaaS / Cloud': [
    {
      id: 'saas-01-escape',
      title: 'Multi-Tenant Kubernetes Pod Container Breakout',
      cwe: 'CWE-250',
      severity: 'Critical',
      exploitability: 'High',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Kubernetes Clusters',
      service: 'Core APIs',
      status: 'Open',
      source: 'CSPM',
      cveId: 'CVE-2024-21626',
      description: 'Flaw in container runtime allows malicious customer workloads to escape isolation and read raw host node memory across tenants.',
    },
    {
      id: 'saas-02-graphql',
      title: 'GraphQL Schema Introspection & Excessive Tenant Data Exposure',
      cwe: 'CWE-200',
      severity: 'High',
      exploitability: 'High',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Multi-Tenant Database',
      service: 'Data Platform',
      status: 'Open',
      source: 'DAST',
      cveId: 'CWE-200',
      description: 'Nested query recursion enables extraction of neighboring enterprise customer account records without tenant boundary checks.',
    },
    {
      id: 'saas-03-ssrf',
      title: 'Server-Side Request Forgery (SSRF) in Outbound Webhook Engine',
      cwe: 'CWE-918',
      severity: 'High',
      exploitability: 'High',
      businessImpact: 'High',
      assetCriticality: 'HIGH',
      complianceImpact: 'Medium',
      asset: 'API Gateway',
      service: 'Core APIs',
      status: 'Open',
      source: 'SAST',
      cveId: 'CVE-2023-38606',
      description: 'Unvalidated webhook destinations allow external callers to query cloud metadata service (169.254.169.254) and steal IAM role tokens.',
    },
    {
      id: 'saas-04-vault',
      title: 'Overprivileged Secrets Vault Service Account Policy',
      cwe: 'CWE-732',
      severity: 'High',
      exploitability: 'Medium',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Secrets Vault',
      service: 'Authentication System',
      status: 'Open',
      source: 'IAM',
      cveId: 'CWE-732',
      description: 'Microservice token contains root read capability across all tenant encryption keys, violating least privilege mandates.',
    },
    {
      id: 'saas-05-ratelimit',
      title: 'Missing API Rate Limiting & Resource Exhaustion (DoS)',
      cwe: 'CWE-770',
      severity: 'Medium',
      exploitability: 'High',
      businessImpact: 'Medium',
      assetCriticality: 'MEDIUM',
      complianceImpact: 'Low',
      asset: 'API Gateway',
      service: 'Customer Portal',
      status: 'Open',
      source: 'SIEM',
      cveId: 'CWE-770',
      description: 'Unauthenticated public search endpoint can be flooded with expensive regex payloads, crashing worker nodes.',
    },
  ],

  Retail: [
    {
      id: 'ret-01-magecart',
      title: 'Payment Card Skimming (Magecart) Script Injection in Checkout',
      cwe: 'CWE-79',
      severity: 'Critical',
      exploitability: 'High',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Payment Gateway',
      service: 'Payment System',
      status: 'Open',
      source: 'DAST',
      cveId: 'CVE-2024-4019',
      description: 'Compromised third-party CDN tag intercepts customer debit/credit card CVVs at checkout and sends them to offshore servers.',
    },
    {
      id: 'ret-02-sqli',
      title: 'SQL Injection in E-Commerce Product Catalog Search',
      cwe: 'CWE-89',
      severity: 'High',
      exploitability: 'High',
      businessImpact: 'High',
      assetCriticality: 'HIGH',
      complianceImpact: 'Medium',
      asset: 'Customer Database',
      service: 'Public Website',
      status: 'Open',
      source: 'SAST',
      cveId: 'CVE-2023-9912',
      description: 'Search parameter concatenation permits union-based SQL extraction of hashed customer passwords and order receipts.',
    },
    {
      id: 'ret-03-pos',
      title: 'Point-of-Sale (POS) API Insecure Credential Caching',
      cwe: 'CWE-522',
      severity: 'High',
      exploitability: 'Medium',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'POS Integration',
      service: 'Payment System',
      status: 'Open',
      source: 'EDR',
      cveId: 'CWE-522',
      description: 'Retail POS terminals store cashier clearance tokens in plain text log files, enabling offline replay attacks.',
    },
    {
      id: 'ret-04-stuffing',
      title: 'Credential Stuffing Vulnerability on Customer Rewards Portal',
      cwe: 'CWE-307',
      severity: 'Medium',
      exploitability: 'High',
      businessImpact: 'Medium',
      assetCriticality: 'MEDIUM',
      complianceImpact: 'Medium',
      asset: 'Customer Database',
      service: 'Customer Portal',
      status: 'Open',
      source: 'SIEM',
      cveId: 'CWE-307',
      description: 'Missing CAPTCHA and velocity limiting allows automated bots to test stolen credentials and drain customer gift cards.',
    },
    {
      id: 'ret-05-s3',
      title: 'Publicly Readable Cloud Storage with Customer Invoices',
      cwe: 'CWE-732',
      severity: 'Medium',
      exploitability: 'High',
      businessImpact: 'High',
      assetCriticality: 'HIGH',
      complianceImpact: 'High',
      asset: 'Inventory ERP',
      service: 'Logistics Platform',
      status: 'Open',
      source: 'CSPM',
      cveId: 'CWE-732',
      description: 'Cloud storage bucket containing shipment addresses and buyer phone numbers configured with Anonymous Read access.',
    },
  ],

  'Critical Infrastructure / Energy': [
    {
      id: 'eng-01-scada',
      title: 'SCADA / Modbus Protocol Command Injection in Substation Telemetry',
      cwe: 'CWE-78',
      severity: 'Critical',
      exploitability: 'High',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Industrial Control Systems',
      service: 'SCADA Network',
      status: 'Open',
      source: 'Threat Intelligence',
      cveId: 'CVE-2024-38112',
      description: 'Industrial control gateway fails to validate Modbus TCP function codes, allowing malicious actors to trip high-voltage breakers.',
    },
    {
      id: 'eng-02-plc',
      title: 'Unauthenticated Firmware Flashing on Turbine Controller PLC',
      cwe: 'CWE-306',
      severity: 'Critical',
      exploitability: 'Medium',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Turbine Controllers',
      service: 'Grid Monitoring',
      status: 'Open',
      source: 'CISA KEV',
      cveId: 'CVE-2023-34362',
      description: 'Programmable Logic Controller lacks cryptographic signature verification on over-the-air firmware updates, risking physical equipment damage.',
    },
    {
      id: 'eng-03-itot',
      title: 'IT/OT Firewall Bypass via Dual-Homed Engineering Laptop',
      cwe: 'CWE-284',
      severity: 'High',
      exploitability: 'High',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Substation Telemetry',
      service: 'SCADA Network',
      status: 'Open',
      source: 'EDR',
      cveId: 'CWE-284',
      description: 'Technician workstation connected concurrently to corporate Wi-Fi and the air-gapped substation field network acts as an unmonitored bridge.',
    },
    {
      id: 'eng-04-coap',
      title: 'Unencrypted CoAP Sensor Telemetry Susceptible to Replay',
      cwe: 'CWE-319',
      severity: 'Medium',
      exploitability: 'High',
      businessImpact: 'High',
      assetCriticality: 'HIGH',
      complianceImpact: 'Medium',
      asset: 'Substation Telemetry',
      service: 'Telemetry Ingestion',
      status: 'Open',
      source: 'SIEM',
      cveId: 'CWE-319',
      description: 'Power grid line temperature and frequency sensors transmit cleartext UDP packets that can be falsified to induce artificial brownouts.',
    },
    {
      id: 'eng-05-vpn',
      title: 'Outdated SSL VPN Gateway with Known Pre-Auth RCE',
      cwe: 'CWE-120',
      severity: 'Critical',
      exploitability: 'High',
      businessImpact: 'High',
      assetCriticality: 'HIGH',
      complianceImpact: 'High',
      asset: 'Cloud Infrastructure',
      service: 'Employee Portal',
      status: 'Open',
      source: 'CISA KEV',
      cveId: 'CVE-2024-21887',
      description: 'Vulnerable perimeter VPN device exploited in the wild by state-sponsored actors to gain initial access to control networks.',
    },
  ],

  Defense: [
    {
      id: 'def-01-c2',
      title: 'Buffer Overflow in Tactical C2 Satellite Uplink Parser',
      cwe: 'CWE-121',
      severity: 'Critical',
      exploitability: 'High',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Classified Data Store',
      service: 'Tactical C2 Network',
      status: 'Open',
      source: 'Threat Intelligence',
      cveId: 'CVE-2024-6001',
      description: 'Stack-based buffer overflow in tactical satellite frame decoder allows remote arbitrary binary injection during combat telemetry sync.',
    },
    {
      id: 'def-02-vault',
      title: 'Side-Channel Electromagnetic Timing Leak in Cryptographic Hardware',
      cwe: 'CWE-385',
      severity: 'Critical',
      exploitability: 'Medium',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Cryptographic Hardware',
      service: 'Secure Communication APIs',
      status: 'Open',
      source: 'SAST',
      cveId: 'CVE-2023-8899',
      description: 'Non-constant-time modular exponentiation enables local attackers to reconstruct top-secret RSA/ECC private keys.',
    },
    {
      id: 'def-03-airgap',
      title: 'USB Mass Storage Auto-Run Vulnerability on Air-Gapped Workstations',
      cwe: 'CWE-829',
      severity: 'High',
      exploitability: 'Medium',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Air-Gapped Vault',
      service: 'Telemetry Platform',
      status: 'Open',
      source: 'EDR',
      cveId: 'CWE-829',
      description: 'Mission planning laptops permit automated execution of malicious LNK shortcuts from removable diagnostic drives.',
    },
    {
      id: 'def-04-supply',
      title: 'Trojanized Third-Party Math Library in Target Acquisition Suite',
      cwe: 'CWE-506',
      severity: 'Critical',
      exploitability: 'High',
      businessImpact: 'Critical',
      assetCriticality: 'VERY HIGH',
      complianceImpact: 'High',
      asset: 'Classified Data Store',
      service: 'Tactical C2 Network',
      status: 'Open',
      source: 'SCA',
      cveId: 'CVE-2024-3094',
      description: 'Compromised upstream dependency injects a covert backdoor into radar target coordinate calculation routines.',
    },
    {
      id: 'def-05-iam',
      title: 'Hardcoded Cryptographic Token in Mission Planning Drone APIs',
      cwe: 'CWE-798',
      severity: 'High',
      exploitability: 'High',
      businessImpact: 'High',
      assetCriticality: 'HIGH',
      complianceImpact: 'High',
      asset: 'Satellite Links',
      service: 'Secure Communication APIs',
      status: 'Open',
      source: 'SAST',
      cveId: 'CWE-798',
      description: 'Hardcoded master operational key found in firmware binary enables unauthorized ground station telemetry hijacking.',
    },
  ],
};

export function getVulnerabilitiesForCompany(
  companyType: CompanyType = 'Banking',
  assets: string[] = [],
  services: string[] = []
): Vulnerability[] {
  const pool = INDUSTRY_VULNERABILITIES[companyType] || INDUSTRY_VULNERABILITIES['Banking'];
  return pool.map((v, idx) => {
    // Attempt to align with company assets/services if possible
    const matchedAsset = assets.find((a) => a.toLowerCase().includes(v.asset.toLowerCase())) || v.asset;
    const matchedService = services.find((s) => s.toLowerCase().includes(v.service.toLowerCase())) || v.service;
    return {
      ...v,
      asset: matchedAsset,
      service: matchedService,
      id: `${companyType.toLowerCase().slice(0, 3)}-${idx + 1}-${v.id}`,
    };
  });
}
