import { SecurityControl } from '../types';

export const SECURITY_CONTROLS_CATALOG: SecurityControl[] = [
  {
    id: 'ctrl-waf-01',
    name: 'Web Application Firewall (WAF)',
    code: 'WAF',
    category: 'Application Protection',
    costINR: 200000, // ₹2.0 Lakhs
    costUSD: 2400,
    riskReduction: 25,
    coverage: ['SQL Injection', 'Cross-Site Scripting', 'API Abuse', 'OWASP Top 10', 'Cart Tampering'],
    implementationTime: '1-2 weeks',
    dependencies: [],
    supportedVulnerabilities: ['bnk-01-sqli', 'rtl-01-cart', 'rtl-03-xss'],
    description: 'Cloud-native WAF inspecting L7 traffic, stopping SQL injection payloads and malicious bots before hitting backend application code.',
  },
  {
    id: 'ctrl-mfa-02',
    name: 'Multi-Factor Authentication (MFA & SSO)',
    code: 'MFA',
    category: 'Identity & Access',
    costINR: 120000, // ₹1.2 Lakhs
    costUSD: 1450,
    riskReduction: 22,
    coverage: ['Weak Password', 'Credential Stuffing', 'Session Hijacking', 'Account Takeover'],
    implementationTime: '1 week',
    dependencies: [],
    supportedVulnerabilities: ['bnk-04-pwd', 'hlth-05-auth', 'rtl-04-loyalty'],
    description: 'FIDO2 / TOTP hardware and push-based multi-factor authentication protecting employee and customer administrative portals.',
  },
  {
    id: 'ctrl-patch-03',
    name: 'Automated Patch & Vulnerability Management',
    code: 'PATCH',
    category: 'Software & Infrastructure',
    costINR: 80000, // ₹80,000
    costUSD: 1000,
    riskReduction: 18,
    coverage: ['Outdated Library', 'Known RCE Exploits', 'Zero-Day Vulnerabilities'],
    implementationTime: '3-5 days',
    dependencies: [],
    supportedVulnerabilities: ['bnk-05-lib', 'enr-02-rtu', 'saas-05-redis'],
    description: 'Continuous automated CVE scanning and container patch deployment pipeline eliminating vulnerable open-source dependencies.',
  },
  {
    id: 'ctrl-api-04',
    name: 'API Security Gateway & Secret Vault',
    code: 'API_SEC',
    category: 'API & Secrets Protection',
    costINR: 250000, // ₹2.5 Lakhs
    costUSD: 3000,
    riskReduction: 20,
    coverage: ['Exposed API Token', 'Broken Object Level Auth', 'IDOR', 'Rate Limit Abuse'],
    implementationTime: '2 weeks',
    dependencies: ['ctrl-waf-01'], // Requires WAF / Gateway foundation
    supportedVulnerabilities: ['bnk-06-api', 'hlth-03-idor', 'saas-02-graphql'],
    description: 'Runtime API anomaly detector, automated token rotation, and mutual TLS encryption for B2B financial and cloud integrations.',
  },
  {
    id: 'ctrl-edr-05',
    name: 'Next-Gen Endpoint Detection & Response (EDR)',
    code: 'EDR',
    category: 'Host & Endpoint Defense',
    costINR: 300000, // ₹3.0 Lakhs
    costUSD: 3600,
    riskReduction: 26,
    coverage: ['Ransomware Lateral Movement', 'Memory Injections', 'Privilege Escalation', 'USB Exploitation'],
    implementationTime: '2-3 weeks',
    dependencies: [],
    supportedVulnerabilities: ['bnk-07-ransom', 'hlth-06-ransom', 'def-03-airgap', 'rtl-02-pos'],
    description: 'Behavioral heuristic agent isolating compromised endpoints and blocking automated SMB ransomware propagation within 60 seconds.',
  },
  {
    id: 'ctrl-cloud-06',
    name: 'Cloud Security Posture & K8s Guardrails (CSPM)',
    code: 'CLOUD_SEC',
    category: 'Cloud Infrastructure',
    costINR: 280000, // ₹2.8 Lakhs
    costUSD: 3400,
    riskReduction: 22,
    coverage: ['Cloud Misconfiguration', 'Public S3 Buckets', 'Container Escape', 'Over-privileged IAM Roles'],
    implementationTime: '1 week',
    dependencies: [],
    supportedVulnerabilities: ['saas-01-escape', 'saas-03-secrets', 'enr-05-iam'],
    description: 'Continuous IaC drift detection and runtime admission controller preventing container breakout and multi-tenant cloud exposure.',
  },
  {
    id: 'ctrl-dlp-07',
    name: 'Data Loss Prevention & Field-Level Tokenization (DLP)',
    code: 'DLP',
    category: 'Data Protection',
    costINR: 350000, // ₹3.5 Lakhs
    costUSD: 4200,
    riskReduction: 28,
    coverage: ['Sensitive Data Exposure', 'PII Exfiltration', 'PHI Exposure', 'Unencrypted Database'],
    implementationTime: '3 weeks',
    dependencies: [],
    supportedVulnerabilities: ['bnk-02-data', 'hlth-01-ehr', 'rtl-03-xss'],
    description: 'Format-preserving encryption and database field tokenization preventing raw credit card, PHI, and PII exposure in memory and dumps.',
  },
  {
    id: 'ctrl-iam-08',
    name: 'Zero-Trust Privileged Access Management (PAM)',
    code: 'IAM_PAM',
    category: 'Identity & Access',
    costINR: 220000, // ₹2.2 Lakhs
    costUSD: 2600,
    riskReduction: 20,
    coverage: ['Broken Authentication', 'Privilege Escalation', 'Orphaned Admin Accounts'],
    implementationTime: '2 weeks',
    dependencies: ['ctrl-mfa-02'], // Requires MFA base
    supportedVulnerabilities: ['bnk-03-auth', 'hlth-05-auth', 'enr-04-bridge'],
    description: 'Just-in-time credential checkout, session recording, and least-privilege role binding for infrastructure administrators.',
  },
  {
    id: 'ctrl-ztna-09',
    name: 'Zero-Trust Network Access & Microsegmentation (ZTNA)',
    code: 'ZTNA',
    category: 'Network Architecture',
    costINR: 450000, // ₹4.5 Lakhs
    costUSD: 5400,
    riskReduction: 30,
    coverage: ['Lateral Movement', 'Subnet Traversal', 'Air-Gap Bridging', 'Unsegmented Networks'],
    implementationTime: '3-4 weeks',
    dependencies: [],
    supportedVulnerabilities: ['enr-04-bridge', 'def-03-airgap', 'saas-04-ddos'],
    description: 'Software-defined perimeter replacing flat corporate VPNs with identity-aware ephemeral tunnels preventing lateral network hopping.',
  },
  {
    id: 'ctrl-siem-10',
    name: 'Next-Gen SIEM & Automated SOAR Platform',
    code: 'SIEM_SOAR',
    category: 'Threat Detection & Response',
    costINR: 500000, // ₹5.0 Lakhs
    costUSD: 6000,
    riskReduction: 32,
    coverage: ['Threat Intel Correlation', 'Zero-Day Detection', 'Automated Containment', 'Audit Compliance'],
    implementationTime: '3-4 weeks',
    dependencies: [],
    supportedVulnerabilities: ['enr-03-firmware', 'def-05-iam', 'bnk-07-ransom'],
    description: 'AI-driven security information correlation engine analyzing telemetry across 9 ingestion pipelines with automated runbook response.',
  },
  {
    id: 'ctrl-ot-11',
    name: 'Industrial OT / SCADA Unidirectional Security Gateway',
    code: 'OT_DIODE',
    category: 'Operational Technology (OT)',
    costINR: 600000, // ₹6.0 Lakhs
    costUSD: 7200,
    riskReduction: 38,
    coverage: ['SCADA Exploits', 'Modbus Spoofing', 'PLC Firmware Hijacking', 'Turbine Tampering'],
    implementationTime: '4 weeks',
    dependencies: [],
    supportedVulnerabilities: ['enr-01-scada', 'enr-02-rtu', 'enr-03-firmware'],
    description: 'Hardware optical data diode enforcing physical one-way telemetry flow, completely isolating SCADA and RTU networks from IP attacks.',
  },
  {
    id: 'ctrl-hsm-12',
    name: 'Hardware Security Module (HSM) & Quantum-Safe Vault',
    code: 'HSM_CRYPTO',
    category: 'Cryptographic Security',
    costINR: 550000, // ₹5.5 Lakhs
    costUSD: 6600,
    riskReduction: 35,
    coverage: ['Cryptographic Side-Channels', 'Master Key Leaks', 'Firmware Forgery', 'Satellite Telemetry'],
    implementationTime: '3-4 weeks',
    dependencies: [],
    supportedVulnerabilities: ['def-01-crypto', 'def-02-key', 'def-05-iam'],
    description: 'FIPS 140-3 Level 4 tamper-resistant cryptographic co-processor safeguarding top-secret RSA/ECC keys against side-channel extraction.',
  },
  {
    id: 'ctrl-med-13',
    name: 'Clinical IoMT Device Isolation & Telemetry Gate',
    code: 'MED_ISOLATION',
    category: 'Clinical IoT / IoMT',
    costINR: 400000, // ₹4.0 Lakhs
    costUSD: 4800,
    riskReduction: 34,
    coverage: ['DICOM PACS Exploit', 'Clinical Infusion Tampering', 'Bedside Monitor Interception', 'EHR Ransomware'],
    implementationTime: '3 weeks',
    dependencies: [],
    supportedVulnerabilities: ['hlth-02-dicom', 'hlth-04-iot', 'hlth-06-ransom'],
    description: 'Dedicated clinical device security appliance profiling DICOM and HL7 traffic, preventing unauthenticated protocol tampering.',
  },
  {
    id: 'ctrl-fraud-14',
    name: 'Real-Time Financial Anomaly & Anti-Fraud Engine',
    code: 'FRAUD_SHIELD',
    category: 'Financial Risk & Fraud',
    costINR: 480000, // ₹4.8 Lakhs
    costUSD: 5800,
    riskReduction: 32,
    coverage: ['Payment Gateway Settlement Tampering', 'NEFT/RTGS Wire Hijack', 'Loyalty Balance Tampering', 'Ledger Fraud'],
    implementationTime: '3-4 weeks',
    dependencies: ['ctrl-waf-01'],
    supportedVulnerabilities: ['bnk-01-sqli', 'bnk-06-api', 'rtl-01-cart', 'rtl-04-loyalty'],
    description: 'Behavioral payment stream anomaly monitor flagging high-velocity transaction deviations and fraudulent settlement ledger edits.',
  },
  {
    id: 'ctrl-supply-15',
    name: 'Software Supply Chain Security & SBOM Attestation',
    code: 'SUPPLY_SEC',
    category: 'Software Supply Chain',
    costINR: 200000, // ₹2.0 Lakhs
    costUSD: 2400,
    riskReduction: 20,
    coverage: ['Trojanized Dependencies', 'Backdoored Math Libraries', 'Upstream Package Poisoning'],
    implementationTime: '1-2 weeks',
    dependencies: [],
    supportedVulnerabilities: ['def-04-supply', 'bnk-05-lib', 'saas-01-escape'],
    description: 'Automated cryptographic SBOM verification, binary provenance attestation, and real-time dependency typo-squatting prevention.',
  },
];
